version: '2'

services:
    web:
        build:
            context: .
            dockerfile: .docker/apacheDockerfile
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
        links:
            - db:db
    db:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - .docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
